
CREATE TABLE MEDS_DATA_CONTENT_AUD (
    DATA_CONTENT_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    DATA_CONTENT_ID BIGINT(15) NOT NULL,
    DATA BLOB NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (DATA_CONTENT_AUD_ID)
);

CREATE TABLE MEDS_FILE_AUD (
    FILE_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    FILE_ID BIGINT(15) NOT NULL,
    GUID VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EFF_FRM DATETIME NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (FILE_AUD_ID)
);

CREATE TABLE MEDS_IMAGE_AUD (
    IMAGE_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    IMAGE_ID BIGINT(15) NOT NULL,
    FILE_ID BIGINT(15) NOT NULL,
    WIDTH INT(5) NOT NULL,
    HEIGHT INT(5) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (IMAGE_AUD_ID)
);

CREATE TABLE MEDS_USER_AUD (
    USER_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(20) NULL,
    SURNAME VARCHAR(20) NULL,
    PHONE VARCHAR(15) NULL,
    GENDER VARCHAR(9) NULL,
    AGE INT(4) NULL,
    USER_ALLOW_PUSH BOOLEAN NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (USER_AUD_ID)
);

CREATE TABLE MEDS_PERMISSION_AUD (
    PERMISSION_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PERMISSION_ID BIGINT(15) NOT NULL,
    PERMISSION_NAME VARCHAR(50) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PERMISSION_AUD_ID)
);

CREATE TABLE MEDS_USER_PERMISSION_AUD (
    USER_PERMISSION_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    USER_PERMISSION_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    PERMISSION_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (USER_PERMISSION_AUD_ID)
);

CREATE TABLE MEDS_DEVICES_TYPE_AUD (
    DEVICES_TYPE_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    DEVICES_TYPE_ID BIGINT(15) NOT NULL,
    TYPE_NAME VARCHAR(50) NOT NULL,
    CAN_PUSH BOOLEAN NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (DEVICES_TYPE_AUD_ID)
);

CREATE TABLE MEDS_USER_DEVICE_AUD (
    USER_DEVICE_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    USER_DEVICES_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    TYPE_ID BIGINT(15) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DEVICE_PUSH_ID VARCHAR(50) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (USER_DEVICE_AUD_ID)
);

CREATE TABLE MEDS_MEDICAL_AID_AUD (
    MEDICAL_AID_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    MEDICAL_AID_ID BIGINT(15) NOT NULL,
    MEDICAL_AID_NAME BIGINT(50) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (MEDICAL_AID_AUD_ID)
);

CREATE TABLE MEDS_USER_MEDICAL_AID_AUD (
    USER_MEDICAL_AID_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    USER_MEDICAL_AID_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    MEDICAL_AID_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (USER_MEDICAL_AID_AUD_ID)
);

CREATE TABLE MEDS_TRADING_HOUR_AUD (
    TRADING_HOUR_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    TRADING_HOUR_ID BIGINT(15) NOT NULL,
    EFF_FRM TIME NULL,
    EFF_TO TIME NULL,
    BREAK_A_EFF_FRM TIME NULL,
    BREAK_A_EFF_TO TIME NULL,
    BREAK_B_EFF_FRM TIME NULL,
    BREAK_B_EFF_TO TIME NULL,
    OPEN BOOLEAN NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (TRADING_HOUR_AUD_ID)
);

CREATE TABLE MEDS_TRADING_DAY_AUD (
    TRADING_DAY_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    TRADING_DAY_ID BIGINT(15) NOT NULL,
    MONDAY_ID BIGINT(15) NOT NULL,
    TUESDAY_ID BIGINT(15) NOT NULL,
    WEDNESDAY_ID BIGINT(15) NOT NULL,
    THURSDAY_ID BIGINT(15) NOT NULL,
    FRIDAY_ID BIGINT(15) NOT NULL,
    SATURDAY_ID BIGINT(15) NOT NULL,
    SUNDAY_ID BIGINT(15) NOT NULL,
    PUBIC_HOLIDAY_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (TRADING_DAY_AUD_ID)
);

CREATE TABLE MEDS_FIELD_AUD (
    FIELD_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    FIELD_ID BIGINT(15) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MAP_COLOR VARCHAR(6) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (FIELD_AUD_ID)
);

CREATE TABLE MEDS_PRACTICE_AUD (
    PRACTICE_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PRACTICE_ID BIGINT(15) NOT NULL,
    NAME VARCHAR(50) NULL,
    EMAIL VARCHAR(50) NOT NULL,
    LONGITUDE FLOAT(30) NOT NULL,
    LATITUDE FLOAT(30) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    TRADING_DAY_ID BIGINT(200) NOT NULL,
    PHONE VARCHAR(20) NULL,
    FEE FLOAT(30) NULL,
    IMAGE_ID BIGINT(30) NOT NULL,
    BIO_ID BIGINT(30) NOT NULL,
    EFF_FRM DATETIME NOT NULL,
    EFF_TO DATETIME NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PRACTICE_AUD_ID)
);

CREATE TABLE MEDS_PRACTICE_USER_AUD (
    PRACTICE_USER_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PRACTICE_USER_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    PRACTICE_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PRACTICE_USER_AUD_ID)
);

CREATE TABLE MEDS_PRACTICE_FIELD_AUD (
    PRACTICE_FIELD_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PRACTICE_FIELD_ID BIGINT(15) NOT NULL,
    FIELD_ID BIGINT(15) NOT NULL,
    PRACTICE_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PRACTICE_FIELD_AUD_ID)
);

CREATE TABLE MEDS_PRACTICE_MEDICAL_AID_AUD (
    PRACTICE_MEDICAL_AID_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PRACTICE_MEDICAL_AID_ID BIGINT(15) NOT NULL,
    PRACTICE_ID BIGINT(15) NOT NULL,
    MEDICAL_AID_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PRACTICE_MEDICAL_AID_AUD_ID)
);

CREATE TABLE MEDS_DOCTOR_AUD (
    DOCTOR_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    DOCTOR_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    ICON_ID BIGINT(15) NOT NULL,
    IMAGE_ID BIGINT(15) NOT NULL,
    TRADING_DAY_ID BIGINT(15) NOT NULL,
    BIO_ID BIGINT(15) NOT NULL,
    EFF_FRM DATETIME NOT NULL,
    EFF_TO DATETIME NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (DOCTOR_AUD_ID)
);

CREATE TABLE MEDS_DOCTOR_USER_AUD (
    DOCTOR_USER_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    DOCTOR_USER_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    DOCTOR_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (DOCTOR_USER_AUD_ID)
);

CREATE TABLE MEDS_DOCTOR_FIELD_AUD (
    DOCTOR_FIELD_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    DOCTOR_FIELD_ID BIGINT(15) NOT NULL,
    FIELD_ID BIGINT(15) NOT NULL,
    DOCTOR_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (DOCTOR_FIELD_AUD_ID)
);

CREATE TABLE MEDS_DOCTOR_PRACTICE_AUD (
    DOCTOR_PRACTICE_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    MEDS_DOCTOR_PRACTICE_ID BIGINT(15) NOT NULL,
    PRACTICE_ID BIGINT(15) NOT NULL,
    DOCTOR_ID BIGINT(15) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (DOCTOR_PRACTICE_AUD_ID)
);

CREATE TABLE MEDS_REVIEW_AUD (
    REVIEW_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    REVIEW_ID BIGINT(15) NOT NULL,
    DOCTOR_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    RATING INT(1) NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    EFF_FRM DATETIME NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (REVIEW_AUD_ID)
);

CREATE TABLE MEDS_APPOINTMENT_AUD (
    APPOINTMENT_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    APPOINTMENT_ID BIGINT(15) NOT NULL,
    DOCTOR_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    NOTE_ID BIGINT(15) NULL,
    EXPECTED_FRM DATETIME NOT NULL,
    EXPECTED_TO DATETIME NOT NULL,
    ACTUAL_FRM DATETIME NULL,
    ACTUAL_TO DATETIME NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (APPOINTMENT_AUD_ID)
);

CREATE TABLE MEDS_PRESCRIPTION_AUD (
    PRESCRIPTION_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PRESCRIPTION_ID BIGINT(15) NOT NULL,
    APPOINTMENT_ID BIGINT(15) NOT NULL,
    DOCTOR_ID BIGINT(15) NOT NULL,
    USER_ID BIGINT(15) NOT NULL,
    FILE_ID BIGINT(15) NOT NULL,
    EFF_FRM DATETIME NOT NULL,
    EFF_TO DATETIME NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PRESCRIPTION_AUD_ID)
);

CREATE TABLE MEDS_PRESCRIPTION_ITEM_AUD (
    PRESCRIPTION_ITEM_AUD_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
    PRESCRIPTION_ITEM_ID BIGINT(15) NOT NULL,
    PRESCRIPTION_ID BIGINT(15) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    REV INT NOT NULL,
    REVTYPE TINYINT NOT NULL,

    PRIMARY KEY (PRESCRIPTION_ITEM_AUD_ID)
);

CREATE TABLE REVINFO (
    REV INT NOT NULL AUTO_INCREMENT,
    REVTSTMP BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    DATE_CHANGED DATETIME NOT NULL,

    PRIMARY KEY (REV)
)